---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: toktoktok
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: myimage=alexvplle/toktoktok
    argocd-image-updater.argoproj.io/myimage.update-strategy: newest-build
    argocd-image-updater.argoproj.io/myimage.helm.image-spec: image.repository:image.tag
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-ssh
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: https://github.com/alexvplle/infrastructure_as_code
    targetRevision: main
    path: argocd/charts/toktoktok
  destination:
    server: https://kubernetes.default.svc
    namespace: toktoktok
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
