replicaCount: 1
image:
  repository: alexvplle/toktoktok
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: toktoktok.alexvplle.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: toktoktok-tls
      hosts:
        - toktoktok.alexvplle.com

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}
